---
title: "Assignments"
---

### Week 1

#### Register for Github, DataCamp, and REDCap accounts

- send userid's to Tell by email

#### Complete Data Camp intro course

- "Data Management for Critical Care Research" course in Data Camp
     - "Orientation" chapter in the "Working with the RStudio IDE (Part 1)" mini-course
     
- you should have received an invitation

#### Reading: Managing Research Data [here](http://www.ucdenver.edu/research/CCTSI/programs-services/informatics/Documents/Managing-Research-Data.pdf)

- linked videos are optional



### Week 2

- Complete "Intro to basics" chapter in the "Introduction to R" mini-course in Data Camp

- Complete "Reading a .csv file" and "Writing .csv and .tsv files" sections in the "Importing data with `readr`" mini-course in Data Camp

- Download the data from the "PECARN Cardiac Arrest" REDCap database as a .csv file
     - You all have access to the REDCap database
     - Read the data into R using a function from `readr`
     - The data dictionary is in the file repository of the REDCap database





### Week 3

- Complete "Introduction to the Tidyverse" mini-course in Data Camp



### Week 4

- Complete the "Projects" section of the "Intro to the RStudio IDE" mini-course in Data Camp

- Complete "Data Manipulation with R in `dplyr`" mini-course in Data Camp
     - don't sweat the database stuff too much


### Week 5

- Complete "Exploratory Data Analysis" mini-course in Data Camp




#### Optional extra reading/videos: many data management topics are covered [here](http://www.ucdenver.edu/research/CCTSI/programs-services/informatics/Pages/Informatics-Seminar-Learning-Tools-Archive.aspx)

