---
title: "Syllabus"
---

### Week 1 (complete HW 1 prior)

#### General Principles of Data Management (using R)

- Motivation: scientific integrity of your data
- Working with R and RStudio
- Reading data into R using `readr` - introduction


### Week 2 (complete HW 2 prior)

#### Data Backup, File Structure, Intro to Data Transformation

- It's midnight. Do you know where your data are? (just use REDCap and stop worrying about it)
     - it's free
     - it's secure and backed up
     - metadata are built in
- Motivation: .csv is a near-universal data format. 
     - move your data into and out of REDCap as .csv
- `dplyr`! You'll love it - introduction

### Week 3 (complete HW 3 prior)

#### Data Transformation, Intro to Summary Statistics and Data Visualization

- Most of the work in any analysis: data transformation/cleaning
- How best to summarize and visualize your data?

### Week 4 (complete HW 4 prior)

#### How did I do that again? Where the @#$# is that file?

- Reproducibility: scripts are your friends
- Write notes to your future self
- File structure (RStudio projects)

### Week 5 (complete HW 4 prior)

#### Summary Statistics, Intro to Data Visualization

- What does your data mean?
- How best to visualize your data?
- How best to present your data?

